//! Generated by cot CLI 0.6.0 on 2026-04-12 18:10:13+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "task-manager-api";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] = &[
        ::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("task_manager_api__user"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("id"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .primary_key()
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("email"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE)
                        .unique(),
                ],
            )
            .build(),
        ::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("task_manager_api__task"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("id"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .primary_key()
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("user_id"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("title"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("status"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ],
            )
            .build(),
        ::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("task_manager_api__otp"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("email"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .primary_key()
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("code"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ],
            )
            .build(),
    ];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Otp {
    #[model(primary_key)]
    pub email: String,
    pub code: String,
}
#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Task {
    #[model(primary_key)]
    pub id: String,
    pub user_id: String,
    pub title: String,
    pub status: String,
}
#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _User {
    #[model(primary_key)]
    pub id: String,
    #[model(unique)]
    pub email: String,
}
