//! Generated by cot CLI 0.6.0 on 2026-04-16 10:08:01+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "task-manager-api";
    const MIGRATION_NAME: &'static str = "m_0002_auto_20260416_100801";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[
        ::cot::db::migrations::MigrationDependency::migration(
            "task-manager-api",
            "m_0001_initial",
        ),
        ::cot::db::migrations::MigrationDependency::model(
            <crate::models::Otp as ::cot::db::Model>::APP_NAME,
            <crate::models::Otp as ::cot::db::Model>::TABLE_NAME,
        ),
    ];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] = &[
        ::cot::db::migrations::Operation::add_field()
            .table_name(::cot::db::Identifier::new("task_manager_api__otp"))
            .field(
                ::cot::db::migrations::Field::new(
                        ::cot::db::Identifier::new("expires_at"),
                        <chrono::DateTime<chrono::Utc> as ::cot::db::DatabaseField>::TYPE,
                    )
                    .set_null(
                        <chrono::DateTime<
                            chrono::Utc,
                        > as ::cot::db::DatabaseField>::NULLABLE,
                    ),
            )
            .build(),
    ];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Otp {
    #[model(primary_key)]
    pub email: String,
    pub code: String,
    pub expires_at: chrono::DateTime<chrono::Utc>,
}
