//! Generated by cot CLI 0.6.0 on 2026-04-16 10:58:49+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "task-manager-api";
    const MIGRATION_NAME: &'static str = "m_0003_auto_20260416_105849";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[
        ::cot::db::migrations::MigrationDependency::migration(
            "task-manager-api",
            "m_0002_auto_20260416_100801",
        ),
    ];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] = &[
        ::cot::db::migrations::Operation::remove_model()
            .table_name(::cot::db::Identifier::new("task_manager_api__user"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("id"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .primary_key()
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("email"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE)
                        .unique(),
                ],
            )
            .build(),
    ];
}

