//! List of migrations for the current app.
//!
//! Generated by cot CLI 0.6.0 on 2026-04-17 11:25:41+00:00

pub mod m_0001_initial;
/// The list of migrations for current app.
pub const MIGRATIONS: &[&::cot::db::migrations::SyncDynMigration] = &[
    &m_0001_initial::Migration,
];
